### ISSUE TITLE
Name ideas

### ISSUE THREAD

**Issue by iskandr** [hammerlab/mhcdouble#1]
Considering calling this project "mhctwo" or "mhcduo", any other ideas?

**Comment by ihodes** [comment]
I vote for mhcflurry

**Comment by iskandr** [comment]
How about mhcfury?

**Comment by iskandr** [comment]
@tavinathanson suggests "mhcnugget"

**Comment by iskandr** [comment]
@c1ndygao says "bigmhc", pronounced "big mac"

**Comment by iskandr** [comment]
@c1ndygao Might have won with "mhcdouble"

**Comment by iskandr** [comment]
mhcdbl?

**Comment by hammer** [comment]
I'm on the "MHCdouble" train to correspond w/ our capitalization strategy for "MHCflurry"

**Comment by iskandr** [comment]
Also been thinking about convMHC (or convmhc2), since it's a little simpler
to type.

**Comment by iskandr** [comment]
MHCdouble it is!
